### ISSUE TITLE
Latest release not found on NuGet gallery

### ISSUE THREAD

**Issue by jbriggs22** [GibraltarSoftware/Gibraltar.Agent.NLog2#15]
Version on nuget.org is still at 4.7.10
https://www.nuget.org/packages/Gibraltar.Agent.NLog2/

@kendallmiller could you publish the most recent release?

**Comment by kendallmiller** [comment]
Which version of NLog are you looking to use Loupe with?  The versions on NuGet are current for the combination of .NET Framework and NLog <= 4.5.  

The latest NLog45 agent is published as "Loupe.Agent.NLog" and is for .NET Core/.NET Standard and NLog  >= 4.5

https://www.nuget.org/packages/Loupe.Agent.NLog/

**Comment by kendallmiller** [comment]
I've updated the projects to the SDK format, updated their downstream Loupe agents, and published all to NuGet so you should find what you need. But if not- please let me know!

**Comment by jbriggs22** [comment]
Great thank you, I think my issue was mostly just using  **Gibraltar**.Agent.NLog instead of **Loupe**.Agent.NLog. I appreciate the quick updates.
