### ISSUE TITLE
Local log destination

### ISSUE THREAD

**Issue by peske** [GibraltarSoftware/Gibraltar.Agent.NLog2#4]
By default the agent creates log files in c:\ProgramData\Gibraltar...

How this can be changed to some custom location?

Thanks!

**Comment by kendallmiller** [comment]
This is configurable via the folder option in the sessionFile configuration:
[Loupe Documentation - Session File Configuration]( http://www.gibraltarsoftware.com/support/Loupe/Documentation/WebFrame.html#DevelopersReference_SessionFileConfiguration.html)
