### ISSUE TITLE
Update NLog support

### ISSUE THREAD

**Issue by JKSnd** [GibraltarSoftware/Gibraltar.Agent.NLog2#5]
The project I'm working on uses NLog 4. We also like viewing logs with a Loupe client, so we've been including this Gribraltar.Agent.NLog2 package as well. At first glance, binding redirects seem to take care of the version discrepancy.

The issue is that we're experiencing "missing method" exceptions when Error(Exception) calls are made on an NLog logger. I suspect its because of the redirect.

Are there any plans to make an Agent.NLog4 or the like?

**Comment by JKSnd** [comment]
Aaaaaaaaaaand I just noticed that the tip of develop looks to be starting to address exactly this.

**Comment by kendallmiller** [comment]
We are indeed starting to address this but we would definitely value your feedback.  In particular if there are any new features of NLog that you think we should be taking advantage of or problems when using any particular NLog features.  We're hoping on publishing an initial version of this to NuGet soon.

**Comment by JKSnd** [comment]
That's awesome to hear. Thanks for the quick response.

What are the odds you and your team would be willing to do a pre-release alpha? Being ready to integrate this immediately, I could provide a very tight feedback loop for you.

**Comment by kendallmiller** [comment]
We have a NuGet package available to try; I'll see about getting it published to NuGet as a prerelease.  Meanwhile if you wanted you could contact us at support at onloupe.com and we'll respond with the package pronto.

**Comment by kendallmiller** [comment]
I've gone ahead and published it  to NuGet as an alpha package [Loupe Agent for NLog4](https://www.nuget.org/packages/Gibraltar.Agent.NLog4)

**Comment by JKSnd** [comment]
That's great! Thanks so much. Will report back soon!

**Comment by JKSnd** [comment]
So far the logging performance seems just fine. I'm still experiencing the missing method exception as before, but perhaps this means I need to investigate further. It might not be a Gibraltar NLog Agent issue.

**Comment by kendallmiller** [comment]
If you could check into that and let us know where you're seeing that we'd appreciate it.  It doesn't seem to show up in our test suite but, to be fair, we aren't comprehensively using NLog in the tests.

**Comment by JKSnd** [comment]
Welp, as I thought the issue isn't with the NLog agent. The dependency graph of the system we're working on is quite complex, and I hadn't propagated the fix to our logging module properly.

Updating to the NLog4 Agent and then propagating that update properly though our system resulted in no longer seeing the "missing method" exception. We're doing a fantastic amount of logging and everything appears to be reported in Loupe properly.

I don't know what your acceptance criteria are for releases, but this alpha get my thumbs up for what its worth.

**Comment by kendallmiller** [comment]
That's good to hear.  Out of curiosity - what exact version of NLog are you using?

**Comment by JKSnd** [comment]
Our logging library references 4.0.0, as does the application that consumes this library. I haven't experimented with updating the application to the highest 4.x.x available yet though. If it would help you solidify confidence in the alpha, I could do so.

**Comment by kendallmiller** [comment]
I've gone ahead and published to NuGet for 4.0.  We are curious for feedback on version 4.4 as we've had one customer talk to us about an issue with getting source code information under 4.4, however they were also using NLog behind yet another log system so we weren't clear on what level the problem was introduced at.

**Comment by JKSnd** [comment]
Nice! I won't stress about it then. Things are working nicely for me as-is.

I'll pipe up if I notice anything wild. Thanks so much for your responsiveness! Big +1 to you, sir.
